---

- hosts: opd_ansible-01
  tasks:
  - name: git pull filebeat hosts config
    become: yes
    become_user: dearxuany
    shell: cd /data/app/ansible-deploy/alihn1-playbook/roles/filebeat/files/elk-filebeat-conf && git pull origin prd

- hosts: prd_app-03, prd_app-04
  tasks:
  - name: Copy Package
    copy: src=/data/app/ansible-deploy/alihn1-playbook/roles/filebeat/files/filebeat.tar.gz  dest=/data/usr/local/src/filebeat.tar.gz
  - name: Tar Packeage
    shell: cd /data/usr/local; tar -xvz -f /data/usr/local/src/filebeat.tar.gz -C /data/usr/local
  - name: Copy Filebeat Config
    copy: src=/data/app/ansible-deploy/alihn1-playbook/roles/filebeat/files/elk-filebeat-conf/{{ server_names }}-filebeat.yml dest=/data/usr/local/filebeat/filebeat.yml
  - name: Copyt Filebeat Startup Script
    copy: src=/data/app/ansible-deploy/alihn1-playbook/roles/filebeat/files/start_filebeat.sh dest=/data/usr/local/filebeat/start_filebeat.sh
  - name: Copy Filebeat Startup File To Systemd
    copy: src=/data/app/ansible-deploy/alihn1-playbook/roles/filebeat/files/filebeat.service dest=/etc/systemd/system/filebeat.service
  - name: Reload Filebeat Systemd Unit File
    shell: systemctl daemon-reload
  - name: open user lock
    become: yes
    become_user: dearxuany
    shell: chattr -i /etc/passwd /etc/shadow /etc/group /etc/gshadow
  - name: Create Filebeat User
    become: yes
    become_user: dearxuany
    user: name=elk state=present createhome=no shell=/usr/sbin/nologin
  - name: shutdown user lock
    become: yes
    become_user: dearxuany
    shell: chattr +i /etc/passwd /etc/shadow /etc/group /etc/gshadow
  - name: Modify Filebeat Basedir Permission
    file: path=/data/usr/local/filebeat owner=elk group=elk recurse=yes
  - name: Create Filebeat Start Log Dir
    file: path=/data/var/log/filebeat state=directory owner=elk group=elk mode=0755
  - name: Start Filebeat With System Start
    shell: systemctl enable filebeat 
  - name: Create Filebeat Start Log
    file: path=/data/var/log/filebeat/filebeat-start.log state=touch owner=elk group=elk mode=0644
  - name: Run Filebeat by ELK User
    shell: systemctl restart filebeat
