---

- hosts: prd_canal-01
  tasks:
  - copy: src=files/jdk-8u171-linux-x64.tar.gz dest=/data/usr/local/src/jdk.tar.gz
  - name: Tar Package
    shell: cd /data/usr/local; tar -xvz -f /data/usr/local/src/jdk.tar.gz -C /data/usr/local
  - name: Rename jdk
    shell: mv /data/usr/local/jdk1.8.0_171 /data/usr/local/jdk
  - name: Set Java Path
    shell: sed -i.bak '$a export JAVA_HOME=/data/usr/local/jdk\nexport PATH=$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH\nexport CLASSPATH=.:$JAVA_HOME/lib:$JAVA_HOME/jre/lib:$JAVA_HOME/lib/tools.jar' /etc/profile
  - name: Source Profile
    become: yes
    become_user: dearxuany
    shell: source /etc/profile
  - name: wait for seconds
    shell: sleep 10s
  - name: check java
    shell: which java
    register: cmd_output
  - name: show command stdout
    debug: var=cmd_output verbosity=0
