---

- hosts: dev_liyunxuan-01
  become: yes
  become_user: dearxuany
  tasks:
  - name: Copy Package
    copy: src=files/elasticsearch-7.1.1-linux-x86_64.tar.gz dest=/data/usr/local/src/elasticsearch.tar.gz
  - name: Tar Package
    become: yes
    become_user: dearxuany
    shell: tar -xvz -f /data/usr/local/src/elasticsearch.tar.gz -C /data/usr/local
  - name: Rename elasticsearch
    shell: mv /data/usr/local/elasticsearch-7.1.1 /data/usr/local/elasticsearch
  - name: Copy Elasticsearch Startup Script
    copy: src=files/start_elasticsearsh.sh dest=/data/usr/local/elasticsearch/start_elasticsearsh.sh
  - name: open user lock
    become: yes
    become_user: dearxuany
    shell: chattr -i /etc/passwd /etc/shadow /etc/group /etc/gshadow
  - name: Create elk User
    become: yes
    become_user: dearxuany
    user: name=elk state=present createhome=no shell=/bin/bash
  - name: shutdown user lock
    become: yes
    become_user: dearxuany
    shell: chattr +i /etc/passwd /etc/shadow /etc/group /etc/gshadow
  - name: Modify Elasticsearch Basedir Permission
    file: path=/data/usr/local/elasticsearch owner=elk group=elk recurse=yes
  - name: Create Elasticsearch Start Log Dir
    file: path=/data/var/log/elasticsearch state=directory owner=elk group=elk mode=0755
  - name: Create Elasitcsearch Start Log
    file: path=/data/var/log/elasticsearch/elasticsearch-start.log state=touch owner=elk group=elk mode=0644
  - name: Create Elasticsearch Data Dir
    file: path=/data/data/elasticsearch state=directory owner=elk group=elk mode=0755
  - name: set the number of open file handles
    become: yes
    become_user: dearxuany
    lineinfile:
      dest: /etc/security/limits.conf
      insertbefore: '{{ item.insertbefore }}'
      line: '{{ item.line }}'
    with_items:
      - { insertbefore: '^# End of file', line: 'elk soft nofile 65536'}
      - { insertbefore: '^# End of file', line: 'elk hard nofile 65536'}
      - { insertbefore: '^# End of file', line: 'elk soft memlock unlimited'}
      - { insertbefore: '^# End of file', line: 'elk hard memlock unlimited'}
  - name: increase max virtual memory areas
    become: yes
    become_user: dearxuany
    lineinfile:
      dest: /etc/sysctl.conf
      insertafter: '{{ item.insertafter }}'
      line: '{{ item.line }}'
    with_items:
      - { insertafter: '^# For more information', line: 'vm.max_map_count=262144'}
      - { insertafter: '^# For more information', line: 'vm.swappiness=0'}
  - name: update the  max virtual memory areas
    shell: sudo sysctl -p
      
      
